### ISSUE TITLE
does no work

### ISSUE THREAD

**Issue by jhaggle** [Ashok93/Structure-From-Motion-SFM-#1]
This does not work. Get the following error when trying to run

FileNotFoundError: [Errno 2] No such file or directory:  sfm/Structure-From-Motion-SFM-/data/calibration/camera_observatory.txt'

**Comment by mochsner** [comment]
Yeah this is generally out-of-date, it seems. 

@Ashok93 Do you have any information on what versions of python and where the packages might've been installed from? I'm using Anaconda for matplotlib numpy mayavi scipy, but then pip install `opencv-python`.

When using 3.7 (which was out at the time of this project creation), mayavi seems to have a failure.

**Comment by Ashok93** [comment]
@jhaggle @mochsner Sorry for the delayed response. Unfortunately, I am not maintaining this repository anymore, this was done as a part of my learning during my University courses. I hope the code could serve as template for learning :pray:
