### ISSUE TITLE
thank you for your code but i have some question.

### ISSUE THREAD

**Issue by DLbeginner** [Ashok93/Structure-From-Motion-SFM-#2]
i use my own dataset to make point cloud with sfm and your code help me to do that.

but i have a question with your code.
 the code indicates this error log : Reprojection Error [9.41775483 1.69068424]

it is not just one line, but shows many lines of that error. can you explain me why this happen?

**Comment by Ashok93** [comment]
@DLbeginner  Sorry for the delayed response. Unfortunately, I am not maintaining this repository anymore, this was done as a part of my learning during my University courses. I hope the code could serve as template for learning 🙏
